import { Inter } from 'next/font/google'
import { type Metadata } from 'next'
import './globals.css'

export interface RootLayoutProps {
  children: React.ReactNode
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: Readonly<RootLayoutProps>): React.ReactNode {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
